---
# install tezos as tezos user
#
- name: Check that signer present
  stat:
    path: /home/tezos/tezos/tezos-signer
  register: stat_result

- git:
    repo: 'https://gitlab.com/tezos/tezos.git'
    dest: /home/tezos/tezos
    version: '{{ tezos_version }}'
  when: stat_result.stat.exists == False 
    
- name: install ocaml environment
  shell: | 
    cd /home/tezos/tezos
    opam init --bare --auto-setup
    opam switch create tezos ocaml-base-compiler.4.07.1
    eval $(opam env)
    . $HOME/.cargo/env
    make build-deps
    make
  register: tezosinstall
  when: stat_result.stat.exists == False 

- debug: msg="{{ tezosinstall.stdout }}"
  when: stat_result.stat.exists == False 

- debug: msg="{{ tezosinstall.stderr }}"
  when: stat_result.stat.exists == False 

- name: Add tezos bin dir to $PATH for tezos user.
  lineinfile:
    dest: /home/tezos/.bashrc
    line: PATH=$PATH:/home/tezos/tezos/

    ## the command prints the command to run, hence the $(...)
    #- name: import ledger key
    #  shell:
    #    $(tezos-signer list connected ledgers | grep "import secret key" | grep ed25519 | sed -e "s|0'/0'|2'/2'|")

